- repo: local
  hooks:
    - id: terraform-validate
      name: ===> Validating syntax of all .tf files
      entry: tools/terraform-validate.sh
      language: script
      files: \.tf$
    - id: terraform-format
      name: ===> Making sure new terraform code is in a canonical format
      entry: tools/terraform-format.sh
      language: script
      files: \.tf$
    - id: json-lint
      name: ===> Make sure JSON is valid
      entry: tools/json-check.sh
      language: script
      files: \.json$
    - id: terraform-version-check
      name: ===> Checking consistent versions of Terraform
      entry: tools/terraform-version-check.rb
      language: ruby
      files: \.tf$

