AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: |
  Send RDS logs to S3
Resources:
  RDSLogsToS3:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python2.7
      Handler: main.lambda_handler
      Environment:
        Variables:
          RDS_INSTANCE_NAME:
          S3_BUCKET_NAME:
          S3_BUCKET_PREFIX:
          LAST_RECEIVED_FILE: last_received.log
          LOG_NAME_PREFIX: error/
